### ISSUE TITLE
Responding to your RFC

### ISSUE THREAD

**Issue by rmbrunet** [IdentityServer/Documentation#109]
In scopesAndClaims.md the phrase "The 'AlwaysIncludeInIdentityToken' property specifies that a certain should always be part of the identity token, even when an access token for the userinfo endpoint is requested" is missing the word "claim".

Your remark about the Client not been authenticated in the Validation endpoint is a little bit intimidating and I am afraid it would discourage the use of reference tokens (NDC Oslo was an eye opener for me in this respect). Why not just authenticate the client btw?

In the EF implementation I would prefer the Schema to default to "IdentityServer" instead of the database default ('Clients' is very common name); but at least the documentation could just uncomment the Schema lines, use "IdentityServer" for the schema and clarify that it is optional.

In general he documentation is very clear and enjoyable to read.

Just my two cents.

**Comment by leastprivilege** [comment]
Hey, 

you realize you can send PRs for fixing typos etc?

Reference tokens are as "public" as are self-contained ones. They are just not on the wire.

In 2.1 I will add the introspection endpoint (which requires authentication) and then turn of the anonymous access token endpoint by default.

**Comment by rmbrunet** [comment]
Hello,

I thought it was just easier for you to add the missing word instead of dealing with a PR. 

I googled the introspection spec. Very interesting (reading from https://tools.ietf.org/html/draft-ietf-oauth-introspection-11) and close to the current validation endpoint. And I would say that is very much inline with the use of reference tokens as you have insisted more than once.    

In particular the phrase "The authorization server MAY respond differently to different protected resources making the same request.  For instance, an authorization server MAY limit which scopes from a given token are returned for each protected resource to prevent protected resources
from learning more about the larger network than is necessary for its operation"  implies some association between the protected resource and the scopes.  I don't intend to torture you again with the scope-audience equivalence but looking forward to the implementation of introspection in IdentityServer.

Best Regards.
