### ISSUE TITLE
Page references unlisted nuget package

### ISSUE THREAD

**Issue by BrandonBrowning** [IdentityServer/Documentation#122]
https://identityserver.github.io/Documentation/docs/overview/simplestOAuth.html references the nuget package `Thinktecture.IdentityServer3.AccessTokenValidation`, which was unlisted.  After some research it appears `IdentityServer3.AccessTokenValidation` should be referenced instead.

**Comment by brockallen** [comment]
PRs are welcome

**Comment by leastprivilege** [comment]
That's for the 1.x version and thus obsolete. They are unlisted - but install-package will work.

Use the new docs and walkthrough.
