### ISSUE TITLE
Update Nuget Package References

### ISSUE THREAD

**Issue by ryanvgates** [IdentityServer/Documentation#123]
On [MVCGettingStarted](https://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html), the following nuget references are out of date or incorrect.

Current
> install-package Thinktecture.IdentityServer3.AccessTokenValidation

Should be
>install-package IdentityServer3.AccessTokenValidation

Current 
>install-package Thinktecture.IdentityServer3

Should be
>install-package IdentityServer3

If you agree with this, I'll submit a pull request.

**Comment by leastprivilege** [comment]
You are on the wrong version of the docs - try v2

**Comment by ryanvgates** [comment]
Oh I see.
