### ISSUE TITLE
Add walkthrough for JS based apps

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/Documentation#14]

**Comment by mderriey** [comment]
Since an issue has been created already, I suppose we can discuss it here first.

Could you elaborate a bit on what you expect?

Thanks

**Comment by brockallen** [comment]
Brain dump: 

We want to host an IdSvr that allows for a JS-based client. So the hosting and config for IdSvr. Then build a html/JS based app (in VS, I guess) that probably uses the oidc-token-manager to connect to IdSvr to get authentication/profile. Then we need a Web API for the JS app to call. It needs to be configured in IdSvr a s scope, it need to use the IdSvr bearer token MW to protection its API, then the client app needs updating to request the access token/scope for the API and then call the API. Bonus for then showing access token renewal.

**Comment by brockallen** [comment]
There might already be part of the other 2 walks thrus that cover the IdSvr config and building the API. So maybe just copy those as needed... but i think this walk thru should focus more on the JS client. Not sure what the right balance of just referring to the others, or just copying parts of the others.

**Comment by mderriey** [comment]
Thanks Brock.

If I get this right, the first part would be about authenticating a user in the JS app and show information about the user.
The second part would not involve the user per-se but rather the client requesting an access token for the specific scope the API is protected with, then calling the API.

Correct me if I'm wrong.

**Comment by brockallen** [comment]
Yea, something like that. I would want to show one step at a time, starting with authentication. Then show how to then add the API access. Or you can do it in the opposite order -- just one step at a time.

**Comment by mderriey** [comment]
OK, I get the idea.
Since oidc-token-manager is meant to handle implicit flow only, do you have guidance around how the client is supposed to get its access token to call the API? Should I care about trying to make the client secret *secure* or just have it in plain and make a note that this could be enhanced - but can't be considered secure since it lives on the client-side?

**Comment by brockallen** [comment]
Implicit flow supports obtaining an access token. HEre's our sample that show this: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient

**Comment by mderriey** [comment]
Yes but I thought you wanted a client access token and not an end-user
access token.
That's alright.
I get it now.
2 clear steps, one that only does authentication and shows user info.
Another one with an additional scope so that the app can call the API.

**Comment by brockallen** [comment]
Yep

**Comment by mderriey** [comment]
I had a look at the JS client you have in the samples repo.
It looks to me that everything you want is in there, functionally speaking.

Would you be OK with the walkthrough basically building what's in the client?
I didn't forget that you want two clear steps, one for just getting information about the user, which we could do with just requesting identity scopes, resulting in just an identity token being returned, and the second one enriched with an API call, thus requesting resource scopes giving access to an access token we use to call the API.

I also like the fact that you dump the information in the page so the users can see what's going on.

I guess what I want to know is what would you like to be different from that client.
Also, for the screenshots, do you have a specific way for getting them hosted in GitHub? I was thinking  dropping them in the textarea of a new issue and get the URLs from here.

What do you think?
Looking forward to working on this next week.

**Comment by leastprivilege** [comment]
@brockallen can you answer that

wrt pictures - yes that how I did it as well.

**Comment by brockallen** [comment]
> Would you be OK with the walkthrough basically building what's in the client?

Yea, sounds good. I guess it makes sense to use oidc-client to perform all the token validation for us... only problem is that in a more "real" app, I think you'd use the oidc-token-manager instead. You can also take a look at the other JS sample (that uses the token manager). Of course, that one is slightly more complex, and thus perhaps more to document/explain.

**Comment by mderriey** [comment]
I should have been more specific, but I was talking about the sample using
oidc-token-manager (
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient
).

I'm happy to try and replicate this sample in the walkthrough.

Thanks

**Comment by brockallen** [comment]
Perfect, thanks!

**Comment by brockallen** [comment]
Well done and thanks.
