### ISSUE TITLE
TokenClient.cs Not Found

### ISSUE THREAD

**Issue by DasNaughtie** [IdentityServer/Documentation#146]
Hi Guys,

Hope all is well.

Pretty new to IdentityServer and thus far I've not been able to get the SimpleOAuth tutorial to work.  I keep getting the following error:

TokenClient.cs Not Found. 

Search Information
Locating source for 'c:\local\identity\model\IdentityModel\source\IdentityModel.Shared\Client\TokenClient.cs'. Checksum: MD5 {ef ca 99 bd c 3d c2 90 18 65 d5 bd 90 8 75 e3}
The file 'c:\local\identity\model\IdentityModel\source\IdentityModel.Shared\Client\TokenClient.cs' does not exist.
Looking in script documents for 'c:\local\identity\model\IdentityModel\source\IdentityModel.Shared\Client\TokenClient.cs'...
Looking in the projects for 'c:\local\identity\model\IdentityModel\source\IdentityModel.Shared\Client\TokenClient.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\crt\src\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\crt\src\vccorlib\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\src\mfc\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\src\atl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include'...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: c:\local\identity\model\IdentityModel\source\IdentityModel.Shared\Client\TokenClient.cs.
The debugger could not locate the source file 'c:\local\identity\model\IdentityModel\source\IdentityModel.Shared\Client\TokenClient.cs'.

It's then causing a SystemAggregate exception.

Any ideas?

**Comment by brockallen** [comment]
Sorry - just came across this issue (mainly because it's in the wrong repo). If you're still having issues, open a new issue in the IdentityServer repo.
