### ISSUE TITLE
Is there a example to get token from JavaScript with ClientCredentials Flow?

### ISSUE THREAD

**Issue by jrgu86** [IdentityServer/Documentation#167]
Actually i get a token from C# like this;

`static string GetToken()
        {
            string responseString = string.Empty;

            using (var client = new WebClient())
            {
                var values = new NameValueCollection();
                values["grant_type"] = "client_credentials";
                values["scope"] = "ListOfScopes";
                values["client_id"] = "ClientID";
                values["client_secret"] = "ClientSecret";

                var response = client.UploadValues("https://myurl.com/core/connect/token/", values);

                responseString = Encoding.Default.GetString(response);
            }

            return responseString;
         }`

And i get the token, but now, i need to get a token from javascript client.

I tried to do in the same way that the example "JavaScript Implicit Client - Simple" but i get the error;
{"Message":"The requested resource does not support http method 'GET'."}

Somebody can help me?

Thanks in advance.

**Comment by leastprivilege** [comment]
Client credentials flow would be the wrong flow for JS - also it would need to be a POST.

Check the client sample solution for JS samples.

**Comment by jrgu86** [comment]
Thanks for the answer and just a doubt;

Why did you say that ClientCredentials flow would be wrong using in JS?

And just for the record:

`
function GetToken() {

            var http = new XMLHttpRequest();

            var url = "https://myurl/core/connect/token/";

            var params = "grant_type=client_credentials&scope=thescope&client_id=theclientid&client_secret=thesecret";

            http.open("POST", url, true);

            //Send the proper header information along with the request
            http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");

            http.onreadystatechange = function () {
                if (http.readyState == 4 && http.status == 200) {
                    alert(http.responseText);
                }
            }
            http.send(params);
        }`

**Comment by brockallen** [comment]
> Why did you say that ClientCredentials flow would be wrong using in JS?

Because the secret is visible to anyone and they can then also get tokens for your API. You might as well make the API anonymous.

**Comment by StevenTCramer** [comment]
Now that you have the option of RequireClientSecret = false as an option I don't think this is wrong anymore?  Maybe one wants to use JWT even though the public api?
