### ISSUE TITLE
Nice IdSrv3 PluralSight video tutorial 

### ISSUE THREAD

**Issue by totpero** [IdentityServer/Documentation#168]
Hello,
On pluralsight.com is this video tutorial about Idsrv3: [OAuth2 and OpenID Connect Strategies for Angular and ASP.NET](https://app.pluralsight.com/library/courses/oauth2-openid-connect-angular-aspdotnet), author: Kevin Dockx.
Add this link to documentation, is very nice tutorial.

**Comment by brockallen** [comment]
Good idea. Done: https://identityserver.github.io/Documentation/docsv2/resources/home.html
