### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by MagePsycho** [IdentityServer/Documentation#180]
How to refresh the token from CURL?
I can see the code is mentioning about .net https://identityserver.github.io/Documentation/docsv2/advanced/refreshTokens.html

It would be better, if you can mention the similar approach for refreshing token as in https://identityserver.github.io/Documentation/docsv2/endpoints/revocation.html
For example:

> POST /connect/revocation HTTP/1.1
> Host: server.example.com
> Content-Type: application/x-www-form-urlencoded
> Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

This way it's easier for us to understand, how to make an request.

**Comment by leastprivilege** [comment]
Check the spec - they have all the HTTP payload samples.

**Comment by MagePsycho** [comment]
Actually I am using PHP code in client side to consume the service.
So it would be better for me to understand if the request example is given as we have for Revocation.

BTW, where to find this? any link

> Check the spec - they have all the HTTP payload samples.

**Comment by leastprivilege** [comment]
OAuth 2.0 spec:

https://tools.ietf.org/html/rfc6749#section-6
