### ISSUE TITLE
Spelling correction in documentation

### ISSUE THREAD

**Issue by codyskidmore** [IdentityServer/Documentation#238]
See the below link:
https://identityserver.github.io/Documentation/docsv2/configuration/scopesAndClaims.html

"AllowUnrestrictedIntrospection (**_adden_** in v2.3)" => "AllowUnrestrictedIntrospection (**_added_** in v2.3)"

I would correct it myself but don't have permission.

**Comment by brockallen** [comment]
can you send a PR :)

**Comment by codyskidmore** [comment]
I do not know what a PR is, but I will handle it any way you need it.

**Comment by brockallen** [comment]
At the very bottom of that page is a link that says "edit this page".

**Comment by codyskidmore** [comment]
When I clicked "edit this page", it told me I had to fork the docs. I can do that if that is the correct procedure. Sorry about the fuss. Just trying to get this straight before continuing.

**Comment by brockallen** [comment]
Yep, that's how you do it :)

**Comment by codyskidmore** [comment]
Will do.
