### ISSUE TITLE
Document access token validation

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/Documentation#38]

**Comment by bjornhol** [comment]
I'm looking forward to read more about access token validation! 

My understanding is that the access token comes from the OAuth2 "part" of the IdentityServer. But to me it looks like the validation endpoint (connect/accesstokenvalidation) is an extension of OAuth2 (Open ID Connect I assume). So my concern is how this would be following pure OAuth2, besides cryptographic where Authorization Server and token consumer share a key.

Thanks, looking forward 
:+1:

**Comment by leastprivilege** [comment]
This endpont is optional.

OAuth2 does not specify token types - we used either JWT or reference tokens. The latter can be validated by the validation endpoint. The former by any JWT compliant library.

The client sample solution has a sample - documentation: todo ;)

**Comment by bjornhol** [comment]
Thanks!
